name: Node.js CI

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

env:
  isNightly: ${{ contains(github.ref, 'dev') }}
  isReleaseCandidate: ${{ contains(github.ref, 'tags') && contains(github.ref, 'rc-') }}
  isFinalRelease: ${{ contains(github.ref, 'tags') && contains(github.ref, 'release-') }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
    - name: Setup Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Check out source code
      uses: actions/checkout@v2
    
    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build:prod

    - name: Package Distribution
      run: cd dist && zip -r web-config-client.zip *

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: web-config-client
        path: dist/web-config-client.zip

    - name: Update dev tag
      if: env.isNightly == 'true'
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        name: dev
        prerelease: true
        replacesArtifacts: true
        tag: dev
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: dist/web-config-client.zip

    - name: Update latest-rc tag
      if: env.isReleaseCandidate == 'true'
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: latest-rc
        allowUpdates: true
        replacesArtifacts: true
        prerelease: true
        artifacts: dist/web-config-client.zip

    # - name: Release (final)
    #   if: env.isFinalRelease == 'true'
    #   uses: ncipollo/release-action@v1
    #   with:
    #     token: ${{ secrets.GITHUB_TOKEN }}
    #     artifacts: web-config-client.zip
        
    - name: Update latest tag
      if: env.isFinalRelease == 'true'
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: latest
        allowUpdates: true
        replacesArtifacts: true
        artifacts: dist/web-config-client.zip