name: Node.js CI

on:
  push:
    branches:
      - '*'

env:
  isNightly: ${{ contains(github.ref, 'dev') }}
  isFinalRelease: ${{ contains(github.ref, 'master') }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
    - name: Setup Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Check out source code
      uses: actions/checkout@v2
    
    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build:prod

    - name: Package Distribution
      run: cd dist && zip -r web-config-client.zip *

    - name: Release Candidate
      uses: marvinpinto/action-automatic-releases@latest
      if: env.isNightly == 'true'
      with:
        automatic_release_tag: latest-rc
        files: dist/web-config-client.zip
        prerelease: true
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        title: latest-rc

    - name: Release
      uses: marvinpinto/action-automatic-releases@latest
      if: env.isFinalRelease == 'true'
      with:
        automatic_release_tag: latest-rc
        files: dist/web-config-client.zip
        prerelease: false
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        title: stable